import { ICategory } from 'interfaces/category';

export const mockData: ICategory[] = [
  {
    id: '2csd2123',
    name: 'Бургеры',
    products: [
      {
        id: '214saf21',
        name: 'Бургер',
        price: 144,
        delivery: false,
        img: 'burger.png',
      },
      {
        id: '214saf22',
        name: 'Бургер',
        price: 144,
        delivery: false,
        img: 'burger.png',
      },
      {
        id: '214saf23',
        name: 'Бургер',
        price: 144,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '214saf24',
        name: 'Бургер',
        price: 144,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '214saf25',
        name: 'Бургер',
        price: 144,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '214saf26',
        name: 'Бургер',
        price: 144,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '214saf27',
        name: 'Бургер',
        price: 144,
        delivery: true,
        img: 'burger.png',
      },
    ],
  },
  {
    id: '2csd2124',
    name: 'Твистеры',
    products: [
      {
        id: '214saf31',
        name: 'Твистер',
        price: 144,
        delivery: true,
        img: 'shaurma.png',
      },
      {
        id: '214saf32',
        name: 'Твистер',
        price: 144,
        delivery: false,
        img: 'shaurma.png',
      },
      {
        id: '214saf33',
        name: 'Твистер',
        price: 144,
        delivery: true,
        img: 'shaurma.png',
      },
      {
        id: '214saf34',
        name: 'Твистер',
        price: 144,
        delivery: true,
        img: 'shaurma.png',
      },
    ],
  },
  {
    id: '2csd2134',
    name: 'Курица',
    products: [
      {
        id: '214saf41',
        name: '3 стрипса',
        price: 144,
        delivery: false,
        img: 'chicken.png',
      },
      {
        id: '214saf42',
        name: '3 стрипса',
        price: 144,
        delivery: true,
        img: 'chicken.png',
      },
      {
        id: '214saf43',
        name: '3 стрипса',
        price: 144,
        delivery: false,
        img: 'chicken.png',
      },
      {
        id: '214saf44',
        name: '3 стрипса',
        price: 144,
        delivery: true,
        img: 'chicken.png',
      },
    ],
  },
  {
    id: '3csd2134',
    name: 'Баскеты',
    products: [
      {
        id: '314saf41',
        name: 'Баскет XL',
        price: 144,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '314saf42',
        name: 'Баскет XL',
        price: 144,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '314saf43',
        name: 'Баскет XL',
        price: 144,
        delivery: false,
        img: 'burger.png',
      },
      {
        id: '314saf44',
        name: 'Баскет XL',
        price: 144,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '314saf45',
        name: 'Баскет XL',
        price: 144,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '314saf46',
        name: 'Баскет XL',
        price: 144,
        delivery: true,
        img: 'burger.png',
      },
    ],
  },
  {
    id: '5csd2134',
    name: 'Снэки',
    products: [
      {
        id: '414saf41',
        name: '5 Снэков',
        price: 144,
        delivery: false,
        img: 'chicken.png',
      },
      {
        id: '414saf42',
        name: '5 Снэков',
        price: 144,
        delivery: true,
        img: 'chicken.png',
      },
      {
        id: '414saf43',
        name: '5 Снэков',
        price: 144,
        delivery: true,
        img: 'chicken.png',
      },
      {
        id: '414saf44',
        name: '5 Снэков',
        price: 144,
        delivery: true,
        img: 'chicken.png',
      },
      {
        id: '414saf45',
        name: '5 Снэков',
        price: 144,
        delivery: true,
        img: 'chicken.png',
      },
      {
        id: '414saf46',
        name: '5 Снэков',
        price: 144,
        delivery: true,
        img: 'chicken.png',
      },
    ],
  },
  {
    id: '6csd2134',
    name: 'Соусы',
    products: [
      {
        id: '514saf41',
        name: 'Кетчуп',
        price: 10,
        delivery: true,
        img: 'shaurma.png',
      },
      {
        id: '514saf42',
        name: 'Кетчуп',
        price: 10,
        delivery: true,
        img: 'shaurma.png',
      },
      {
        id: '514saf43',
        name: 'Кетчуп',
        price: 10,
        delivery: true,
        img: 'shaurma.png',
      },
    ],
  },
  {
    id: '7csd2134',
    name: 'Напитки',
    products: [
      {
        id: '614saf41',
        name: 'Соса солла',
        price: 100,
        delivery: true,
        img: 'shaurma.png',
      },
      {
        id: '614saf42',
        name: 'Соса солла',
        price: 100,
        delivery: true,
        img: 'shaurma.png',
      },
      {
        id: '614saf43',
        name: 'Соса солла',
        price: 100,
        delivery: false,
        img: 'shaurma.png',
      },
      {
        id: '614saf44',
        name: 'Соса солла',
        price: 100,
        delivery: false,
        img: 'shaurma.png',
      },
    ],
  },
  {
    id: '8csd2134',
    name: 'Кофе и чай',
    products: [
      {
        id: '714saf41',
        name: 'Соса солла',
        price: 100,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '714saf42',
        name: 'Соса солла',
        price: 100,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '714saf43',
        name: 'Соса солла',
        price: 100,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '714saf44',
        name: 'Соса солла',
        price: 100,
        delivery: true,
        img: 'burger.png',
      },
    ],
  },
  {
    id: '9csd2134',
    name: 'Десерты',
    products: [
      {
        id: '814saf41',
        name: 'Кекс',
        price: 100,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '814saf42',
        name: 'Кекс',
        price: 100,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '814saf43',
        name: 'Кекс',
        price: 100,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '814saf44',
        name: 'Кекс',
        price: 100,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '814saf45',
        name: 'Кекс',
        price: 100,
        delivery: true,
        img: 'burger.png',
      },
    ],
  },
  {
    id: '9asd2134',
    name: 'Хиты по 50',
    products: [
      {
        id: '914saf41',
        name: 'Новые носки',
        price: 50,
        delivery: false,
        img: 'chicken.png',
      },
      {
        id: '914saf42',
        name: 'Новые носки',
        price: 50,
        delivery: false,
        img: 'chicken.png',
      },
      {
        id: '914saf43',
        name: 'Новые носки',
        price: 50,
        delivery: true,
        img: 'chicken.png',
      },
      {
        id: '914saf44',
        name: 'Новые носки',
        price: 50,
        delivery: true,
        img: 'chicken.png',
      },
      {
        id: '914saf45',
        name: 'Новые носки',
        price: 50,
        delivery: true,
        img: 'chicken.png',
      },
      {
        id: '914saf46',
        name: 'Новые носки',
        price: 50,
        delivery: true,
        img: 'chicken.png',
      },
      {
        id: '914saf47',
        name: 'Новые носки',
        price: 50,
        delivery: true,
        img: 'chicken.png',
      },
      {
        id: '914saf48',
        name: 'Новые носки',
        price: 50,
        delivery: true,
        img: 'chicken.png',
      },
      {
        id: '914saf49',
        name: 'Новые носки',
        price: 50,
        delivery: true,
        img: 'chicken.png',
      },
      {
        id: '914saf50',
        name: 'Новые носки',
        price: 50,
        delivery: true,
        img: 'chicken.png',
      },
    ],
  },
  {
    id: '1dsd2134',
    name: 'Хиты по 51',
    products: [
      {
        id: '915saf41',
        name: 'Старые носки',
        price: 51,
        delivery: true,
        img: 'burger.png',
      },
      {
        id: '915saf42',
        name: 'Старые носки',
        price: 51,
        delivery: true,
        img: 'burger.png',
      },
    ],
  },
];
